- id: doi:10.1101/2023.07.31.551289
  type: paper
  image: https://www.changliu99.com/uploads/1/3/7/9/137900733/website1_orig.png
  buttons:
    - type: source
      link: https://openneuro.org/datasets/ds004625
  tags:
    - EEG
    - Terrain walking
    - Gait
- id: doi:10.1109/TNSRE.2023.3281356
  type: paper
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7333/10031624/10138592/liu2-3281356-large.gif
  description: Aim to improve the source localization accuracy for EEG studies by determining the error caused by using simplified head models without individual-specific MRIs in both younger and older adults.
  tags:
    - EEG
    - Methods
- id: doi:10.1101/2023.07.10.548298
  tags:
    - Perturbations
    - Gait
    - Modeling

